# Generated by Django 5.0.4 on 2024-05-03 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('howard_web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipopago',
            old_name='nombres',
            new_name='nombre',
        ),
    ]
