# Generated by Django 5.0.4 on 2024-07-07 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('howard_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
