# Generated by Django 5.0.4 on 2024-05-05 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('howard_web', '0003_rename_tipoturno_horario_tipo_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='howard_web.profesor', verbose_name='Profesor'),
        ),
    ]
